classDiagram
    GameController "1" *-- "1" IBanker
    GameController "1" *-- "2" IDice
    GameController "1" *-- "32" ICard
    GameController "1" *-- "2..8" PlayerData
    GameController "1" *-- "1" IBoard
    GameController .. GameStatus
    
    Board ..|> IBoard

    IPlayer "2..8" --* "1" GameController
    IPlayer "0..n" --* "1" Banker
    
    Banker ..|> IBanker
    Banker "1" *-- "0..n" IProperty
    
    PlayerData .. TokenTypes
    PlayerData "1" *-- "0..n" IProperty
    PlayerData "1" *-- "1" ILocationTiles
    PlayerData "1" *-- "0..1" ICard
    
    IBoard *-- ILocationTiles
    
    IProperty <|.. City
    IProperty <|.. RailRoad
    IProperty <|.. Utility

    ILocationTiles <|.. Special
    ILocationTiles <|.. CardTile
    ILocationTiles <|.. City
    ILocationTiles <|.. RailRoad
    ILocationTiles <|.. Utility

    LocationTypes .. ILocationTiles

    ICard .. CardTypes

    IDice <|.. Dice
    
    class GameController {
        -Queue~ICard~ _chanceCards
        -Queue~ICard~ _communityChestCards
        -Dictionary~IPlayer, PlayerData~ _players
        -List~IDice~ _dice
        +IBanker Banker
        -IBoard Board
        +IPlayer CurrentPlayer
        +GameStatus CurrentGameState
        +Action~GameController, IPlayer, ICard~ OnCardEffect
        +Action~IPlayer, int~ OnPlayerMove
        %% Game State
        +GameController(Queue~ICard~ chanceCards, Queue~ICard~ communityChestCards, List~IDice~ dice, List~IPlayer~ players, IBoard board, IBanker banker)
        +StartGame() bool
        +EndGame() bool
        +NextTurn() IPlayer
        +NextTurn(IPlayer nextPlayer) bool
        +Roll() List~int~
        +Winner() IPlayer
        +GetDices() IEnumerable~IDice~
        %%Banker
        +SendMoney(IPlayer player, int amount)
        +SendMoney(IPlayer player, int amount, IPlayer otherPlayer)
        +ReceiveMoney(IPlayer player, int amount)
        +ReceiveMoney(IPlayer player, int amount, IPlayer otherPlayer)
        +HandleAuction(IProperty property) IPlayer
        +HandleMortgage(IPlayer player, IProperty property) bool
        +HandlePropertyRedemption(IPlayer player, IProperty property) bool
        %% Card
        +DrawCard(CardTypes cardType) ICard
        +ExecuteCardEffect(GameController gameController, IPlayer cardTaker, ICard card)
        +GetChanceCards() IEnumerable~ICard~
        +GetCommunityChestCards() IEnumerable~ICard~
        %% Player
        +Move(IPlayer player, int step)
        +KeepCard(IPlayer player, ICard jailFreeCard)
        +GetPlayers() IEnumerable~IPlayer~
        +GetPlayerToken(IPlayer player) TokenTypes
        +GetPlayerLocation(IPlayer player) ILocationTiles
        +GetPlayerProperty(IPlayer player) IEnumerable~IProperty~
        +UpdatePlayerProperty(IPlayer player, IProperty property) bool
        %% Transaction
        +HandleRentPayment(IPlayer payer, IProperty property) bool
        +HandleBankruptcy(IPlayer player) bool
        +BuyProperty(IPlayer buyer, IProperty property) bool
        +BuyHouse(IPlayer buyer, IProperty property, int count) bool
        +BuyHotel(IPlayer buyer, IProperty property, int count) bool
        +BuyCard(IPlayer buyer, int priceOffer, IPlayer seller, ICard card) bool
        +SellProperty(IPlayer seller, params IProperty[] property) bool
        +SellHouse(IPlayer seller, IProperty property, int count) bool
        +SellHotel(IPlayer seller, IProperty property, int count) bool
        +SellCard(IPlayer seller, ICard card, int priceOffer, IPlayer Buyer) bool
        +Trade(IPlayer trader, IProperty property, IPlayer buyer, IProperty property) bool
        +Trade(IPlayer trader, ICard card, IPlayer buyer, IProperty property) bool
        +Trade(IPlayer trader, IProperty property, IPlayer buyer, ICard card) bool
        +PayMortgage(IPlayer player, IProperty location) bool
        %% Board & Property
        +GetBoard() IEnumerable~ILocationTiles~
        +GetLocationById(Guid locationId) ILocationTiles
        +GetAvailableProperty() IEnumerable~ILocationTiles~
        +GetAvailableHouses() int
        +GetAvailableHotels() int
        +UpdateHouseStock(int amount) bool
        +UpdateHotelStock(int amount) bool
    }
    class IBanker {
        <<Interface>>
        +int TotalMoney
        +UpdateMoney(IPlayer player, int amount)
        +UpdatePlayerMoney(IPlayer player, int amount, IPlayer otherPlayer)
        +HandleAuction(IProperty property) IPlayer
    }
    class Banker {
        -int _houseAmounts
        -int _hotelAmounts
        -Dictionary~IPlayer.List~IProperty~~ _mortgagedProperties
        +Banker(int houseAmounts, int hotelAmounts, int totalMoney)
        ~GetAvailableHouses() int
        ~GetAvailableHotels() int
        ~IsEnoughHouses() bool
        ~IsEnoughHotels() bool
        ~UpdateHouseAmount(int amount) bool
        ~UpdateHotelAmount(int amount) bool
        ~UpdateMortgagedProperty(IPlayer owner, IProperty property) bool
    }
    class IBoard {
        <<Interface>>
        +List~ILocationTiles~ Board
    }
    class Board {
        +Board(List~ILocationTiles~ board)
    }
    class ILocationTiles {
        <<Interface>>
        +Guid Id
        +int Position
        +LocationTypes LocationType
        +string Name
        +string Description
    }
    class Special {
        +Special(int position, LocationTypes type, string name, string description)
    }
    class CardTile {
        +CardTile(int position, LocationTypes type, string name, string description)
    }
    class IProperty {
        <<Interface>>
        +int Cost
        +int Rent
        +IPlayer Owner
        +boolean IsMortgaged
        +CalculateRent() int
    }
    class RailRoad {
        +RailRoad(int cost, int rent, int position, LocationTypes type, string name, string description)
    }
    class City {
        +int HouseCost ~get;~
        +int HotelCost ~get;~
        +int NumberOfHouses ~get; private set;~ 
        +int NumberOfHotels ~get; private set;~ 
        +City(int cost, int rent, int position, LocationTypes type, string name, string description)
        ~UpgradeToHotel() bool
        ~BuildHouse(int count) bool
    }
    class Utility {
        +Utility(int cost, int rent, int position, LocationTypes type, string name, string description)
    }
    class IPlayer {
        <<Interface>>
        +Guid Id
        +string Name
    }
    class PlayerData {
        +TokenTypes Token ~get;~
        +int Money
        +List~IProperty~ PropertiesOwned
        +ILocationTiles CurrentPosition
        +ICard JailFreeCard
        +PlayerData(TokenTypes token, int money)
        ~HaveJailFreeCard() bool
    }
    class ICard {
        <<Interface>>
        +Guid Id
        +CardTypes CardType
        +string Description
        +ExecuteCardEffect(GameController gameController, IPlayer cardTaker)
    }
    class IDice {
        <<Interface>>
        +int Side
        +Roll() int
    }
    class Dice {
        +Dice(int side)
    }
    class TokenTypes {
        <<Enumeration>>
        Battleship,
        RaceCar,
        TopHat,
        Cat,
        Penguin,
        RubberDucky,
        Thimble
    }
    class LocationTypes {
        <<Enumeration>>
        City,
        RailRoad,
        Utility,
        ChanceCard,
        CommunityChestCard,
        Corner,
        IncomeTax
    }
    class CardTypes {
        <<Enumeration>>
        Chance,
        CommunityChest
    }
    class GameStatus {
        <<Enumeration>>
        NotInitialized,
        Initialized,
        OnGoing,
        End
    }